#!/bin/bash
set -e

cd contra_directional_couplers

rm -rf dist
rm -rf ../dist

mv auto_cmt_tmm siepic_contradc

python3 -m build
cp -a dist ..

mv siepic_contradc auto_cmt_tmm


#python3 -m twine upload -u __token__ -p ...
